name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install fonts and compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            xelatex -synctex=1 -interaction=nonstopmode resume.tex
            xelatex -synctex=1 -interaction=nonstopmode resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
