name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install fonts and compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            xelatex -interaction=nonstopmode resume.tex
            xelatex -interaction=nonstopmode resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    #if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.5.0
        with:
          provider: cloudflare
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
          account_id: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Fetch artifact from build stage
        uses: actions/download-artifact@master
        with:
          name: PDF

      - name: See where artifact was stored
        run: ls -R

      - name: Upload file to Cloudflare R2
        run: |
          s3cmd put resume.pdf s3://cvdata/resume.pdf
